# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: 技术写作师资班教材
            image:
        nav:
            - item_name: 首页
              item_url: '#'
            - item_name: 通知
              item_url: '#'
            - item_name: 教材
              item_url: '#'
    footer:
        content:
            logo:
                text: 北京大学技术写作师资班
                image:
            address: 北京市大兴区金苑路3403办公室
            copyright: Copyright &copy; 2018. - 北京大学软件与微电子学院 <br>版权所有，侵权必究。
        social_list:
            - network_name: weibo
              profile_url: '#'
            - network_name: wechat
              profile_url: '#'
            - network_name: linkedin
              profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
